# Generated by Django 3.0.3 on 2020-02-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="date_create",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
    ]
