# Generated by Django 3.0.3 on 2020-02-10 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0008_auto_20200210_0143"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment", options={"ordering": ["date_create"]},
        ),
        migrations.AlterModelOptions(
            name="material", options={"ordering": ["-date_pub"]},
        ),
    ]
